### ISSUE TITLE
Feature: Message Input Box

### ISSUE THREAD

**Issue by Dileyz** [THD-AI-2023/Devablos-Project#9]
Well, at least I'm trying to

I want to have finished before today a writable text box so that I ask after what's needed. Maybe start with the event listeners. But before I do that I will do a writable text box and I'll try to make the message send

Hopefully it doesn't take too long, but in any case I'll try my best. Wish me luck

I'll try to update you in the comments

Btw, do I need to do a separate file for each feature? Like in the example you sent us @HlexNC? Or if everything is in the same file is fine? Just to know

**Comment by arudaev** [comment]
Depends on the size @Dileyz. Also, format the title differently, so I know what it is.

**Comment by arudaev** [comment]
Like what text box...?

**Comment by Dileyz** [comment]
text box as for where you write the message you are about to send

**Comment by arudaev** [comment]
Understood. Then call it "message input area"

**Comment by Dileyz** [comment]
I managed to make a first text box in which you can type. I still need to format it but before that I want to make it capture the data.
![imagen_2024-05-13_205237191](https://github.com/THD-AI-2023/Devablos-Project/assets/149291702/ddd70782-3eed-4c95-92e9-2e6cc25ed236)

**Comment by arudaev** [comment]
ok. good

**Comment by arudaev** [comment]
@Dileyz You might find this useful for inspiration.

---

Sure! Below is a simple chat interface for a chatbot using React. I'll provide the code for a default `create-react-app` setup along with the file structure.

### File Structure
```
my-chat-app/
├── node_modules/
├── public/
│   ├── index.html
│   └── ...
├── src/
│   ├── components/
│   │   ├── Chat.js
│   │   ├── ChatInput.js
│   │   ├── Message.js
│   ├── App.js
│   ├── index.js
│   └── App.css
├── .gitignore
├── package.json
├── README.md
└── yarn.lock
```

### Step-by-Step Instructions

1. **Create React App**:
   ```bash
   npx create-react-app my-chat-app
   cd my-chat-app
   ```

2. **Create Components**:
   
   - **Chat.js**:
     ```javascript
     // src/components/Chat.js
     import React, { useState } from 'react';
     import ChatInput from './ChatInput';
     import Message from './Message';
     import './Chat.css';

     const Chat = () => {
       const [messages, setMessages] = useState([]);

       const addMessage = (message, isBot = false) => {
         setMessages([...messages, { text: message, isBot }]);
       };

       return (
         <div className="chat-container">
           <div className="messages">
             {messages.map((msg, index) => (
               <Message key={index} text={msg.text} isBot={msg.isBot} />
             ))}
           </div>
           <ChatInput addMessage={addMessage} />
         </div>
       );
     };

     export default Chat;
     ```

   - **ChatInput.js**:
     ```javascript
     // src/components/ChatInput.js
     import React, { useState } from 'react';

     const ChatInput = ({ addMessage }) => {
       const [input, setInput] = useState('');

       const handleSend = () => {
         if (input.trim()) {
           addMessage(input);
           addMessage('How can I help you today?', true); // Bot response
           setInput('');
         }
       };

       return (
         <div className="chat-input">
           <input
             type="text"
             value={input}
             onChange={(e) => setInput(e.target.value)}
             onKeyPress={(e) => e.key === 'Enter' && handleSend()}
             placeholder="Type a message..."
           />
           <button onClick={handleSend}>Send</button>
         </div>
       );
     };

     export default ChatInput;
     ```

   - **Message.js**:
     ```javascript
     // src/components/Message.js
     import React from 'react';
     import './Message.css';

     const Message = ({ text, isBot }) => {
       return (
         <div className={`message ${isBot ? 'bot' : 'user'}`}>
           {isBot ? '✨' : '😊'} {text}
         </div>
       );
     };

     export default Message;
     ```

3. **Update App.js**:
   ```javascript
   // src/App.js
   import React from 'react';
   import Chat from './components/Chat';
   import './App.css';

   function App() {
     return (
       <div className="App">
         <header className="App-header">
           <h1>Chat with our Bot</h1>
         </header>
         <Chat />
       </div>
     );
   }

   export default App;
   ```

4. **Add Some Basic Styling**:
   
   - **App.css**:
     ```css
     /* src/App.css */
     .App {
       text-align: center;
     }

     .App-header {
       background-color: #282c34;
       min-height: 10vh;
       display: flex;
       flex-direction: column;
       align-items: center;
       justify-content: center;
       font-size: calc(10px + 2vmin);
       color: white;
     }
     ```

   - **Chat.css**:
     ```css
     /* src/components/Chat.css */
     .chat-container {
       display: flex;
       flex-direction: column;
       justify-content: space-between;
       height: 80vh;
       width: 400px;
       margin: auto;
       border: 1px solid #ccc;
       border-radius: 5px;
       padding: 10px;
       background-color: #f9f9f9;
     }

     .messages {
       flex-grow: 1;
       overflow-y: auto;
       margin-bottom: 10px;
     }

     .chat-input {
       display: flex;
     }

     .chat-input input {
       flex-grow: 1;
       padding: 10px;
       border: 1px solid #ccc;
       border-radius: 5px;
     }

     .chat-input button {
       padding: 10px;
       border: none;
       background-color: #007bff;
       color: white;
       cursor: pointer;
       border-radius: 5px;
       margin-left: 5px;
     }
     ```

   - **Message.css**:
     ```css
     /* src/components/Message.css */
     .message {
       padding: 10px;
       margin: 5px 0;
       border-radius: 5px;
       display: flex;
       align-items: center;
     }

     .user {
       background-color: #007bff;
       color: white;
       justify-content: flex-end;
     }

     .bot {
       background-color: #e0e0e0;
       color: black;
       justify-content: flex-start;
     }
     ```

5. **Run the Application**:
   ```bash
   npm start
   ```

This will start the React app and you should see a chat interface where you can interact with the bot. The bot responds with "How can I help you today?" whenever you send a message.

**Comment by arudaev** [comment]
If you are going to follow this example, don't forget to follow the `File Structure` in the root [README.md](https://github.com/THD-AI-2023/Devablos-Project?tab=readme-ov-file#project-structure)

**Comment by Dileyz** [comment]
I'll check it out, bc I already have something more or less built in HTML
```html
<html>
	<head>
		<title>UI
		</title>
		<link rel="stylesheet" type="text/css" href="D:/Java/designs_probably.css">
	</head>

<body>
	<div class="chat_area">
		<div class="message_box">
		<p class="output" id="message_sent">
		</p>
		</div>
	</div>

	<div class="theoretical_decoration">
		<div class="text_box" style="outline:0px;" >
		<input type="text" id="message_input" placeholder="What can I help you with?" maxlength="4000">
		</div>

		<div class="send_button">
		<input type="button" id="onlybtn" value="Send">
		</div>
	</div>

	<script>
		const msg_content = document.getElementById('message_input');
		const sendbtn = document.getElementById('onlybtn');
		const message = document.getElementById('message_sent')

		funtion send_message()
		{
			message.innerHTML = msg_content.value;
		}

		sendbtn.addEventListener('click',send_message);

	</script>

</body>
</html>
```
And CSS aswell
```css
div.chat_area
{
	background-color:#ffffff;
	width:100%;
	height:73%;
	position:absolute;
	top:0;
	left:0;
}

div.theoretical_decoration
{
	background-color:#bbbbbb;
	width:100%;
	height:27%;
	position:absolute;
	bottom:0;
	left:0;
}

div.text_box
{
	background-color:#aaaaaa;
	width:75%;
	height:50%;
	position:absolute;
	bottom:22.5%;
	left:3.5%;
}

div.send_button
{
	background-color:#000000;
	width:87.5px;
	height:87.5px;
	position:absolute;
	bottom:22.5%;
	right:7%;
}

div.message_box
{
	background-color:#444444;
	width:45%;
	height:25%;
	position:absolute;
	bottom:7%;
	right:2.5%;
}

input[type=text]
{
	font-size:1.4em;
}

p.output
{
	color:grey;
	overflow:hidden;
	width:100%;
	height:100%;
	bottom:0;
	left:0;	
	font-size:1.4em;
	text-align:justify;
}
```
I just need to finish designing the funtion that captures the data and then, after that's done, I'll start with the chat functions (the send_message funtion is still not working and I'm trying to figure out why)
